apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: app1
resources:
  - ../../base
commonLabels:
  app: app1
helmCharts:
  - name: app1
    releaseName: trusted-profile-analyzer
    version: 0.0.1-TP1
    repo: https://charts.openshift.io/
    valuesInline:
      name: app1