apiVersion: v1
kind: ConfigMap
metadata:
  name: argocd-rbac-cm
  namespace: argocd
data:
  policy.default: role:readonly
  policy.csv: |
    p, role:org-admin, applications, *, */*, allow
    p, role:org-admin, clusters, get, *, allow
    p, role:org-admin, repositories, get, *, allow
    p, role:org-admin, repositories, create, *, allow
    p, role:org-admin, repositories, update, *, allow
    p, role:org-admin, repositories, delete, *, allow
    p, role:org-admin, projects, get, *, allow
    p, role:org-admin, projects, create, *, allow
    p, role:org-admin, projects, update, *, allow
    p, role:org-admin, projects, delete, *, allow
    p, role:org-admin, logs, get, *, allow
    p, role:org-admin, exec, create, */*, allow
    
    p, role:org-readonly, clusters, get, *, allow
    p, role:org-readonly, projects, get, *, allow  
    p, role:org-readonly, logs, get, *, allow
    p, role:org-readonly, applications, sync, *, allow
    
    p, role:protector-readonly, clusters, get, *, allow
    p, role:protector-readonly, projects, get, *, allow  
    p, role:protector-readonly, logs, get, *, allow
    p, role:protector-readonly, applications, sync, */*, allow
    
    g, misael_oliveira, role:org-admin
  